Cверстал Главную страницу
htmlacademy-htmlcss/1984449-sedona-34 pull request #2
Opened 2022-05-30 14:33 UTC by Moonfaction

Cверстал Главную страницу

2022-05-31 14:10 UTC, mkolotovich requested changes
исправьте комментарии

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      <img src="images/logo.svg" alt="Логотип сайта" width="139px" height="70px">
размеры в атрибутах указываются без указания единиц измерения, иначе валидатор ругается

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +    <img src="images/logo.svg" alt="Логотип сайта" width="139px" height="70px">
размеры в атрибутах указываются без указания единиц измерения, иначе валидатор ругается

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +          <a href="#">Главная</a>
здесь заглушка не нужна, так как мы находимся на этой странице. Удалите атрибут href

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +          <a class="navigation-link navugation-link-current" href="catalog.html">Гостиницы</a>
здесь текущая страница - Главная, а не Гостиницы, и у вас опечатка в имени класса -  navugation-link-current

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +            <span class="visually-hidden">Хочу сюда!</span>
этот текст отображается на странице поэтому класс visually-hidden здесь не нужен, как в принципе и span

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +      <img src="images/Sedona.svg" alt="Седона" width="456.7px" height="212.77px">
вот эти изображения экспортируйте одним файлом, размеры должны указывать целым числом без единиц измерения

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +    <section class="main-images">
если в блоке заголовка нет, то лучше использовать div

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +    <div class="description">
а если заголовок в блоке есть, то лучше как раз использовать section

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +            Седона — не аттракцион для туристов, там течёт своя жизнь
это разметьте тремя тегами

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +            <li>Рекомендуем пожить в настоящем мотеле, всё как в кино!</li>
этот текст относится к предыдущему пункту списка, так что переместите его в предыдущий пункт списка. Тоже самое сделайте и с остальными пунктами списка.

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +              <h1>СУВЕНИРЫ</h1>
тег h1 должен быть один на странице. Заголовки должны идти по порядку от большего к меньшему

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +          Большинство едет в Гранд Каньон и толпится там</li>
это разметьте тремя тегами

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +      <p>
input необходимо оборачивать в форму, а не в параграф

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +          <img src="./images/social-VK.svg" width="24" height="14" alt="Вконтакте">
ошибка в имени файла. У вас нет такого файла. Зато есть файл Social-VK.svg

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +          <img src="./images/social-youtube.svg" width="22" height="17" alt="Ютуб">
ошибка в имени файла. У вас нет такого файла. Зато есть файл Social-youtube.svg

2022-05-31 14:10 UTC, mkolotovich commented on index.html
> +        height="32.9" alt="Логотип академии">
размеры должны быть целым числом

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +          <a class="navigation-link navugation-link-current" href="catalog.html">Гостиницы</a>
страница ссылается сама на себя, здесь не нужен атрибут href

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +            <span class="visually-hidden">Хочу сюда!</span>
этот текст должен быть виден, поэтому здес не нужен класс visually-hidden как и span

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      <button>Сбросить</button>
это всё должно быть внутри формы

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      <button>Сбросить</button>
у этой кнопки должен быть type="reset"

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      <span>Стоимость,₽:</span>
не размечены два поля ввода от и до

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +    <h1>Найдено страниц:38</h1>
h1 должен быть один на странице

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      <option value="cheap">Сначала дешёвое</option>
укажите атрибут selected

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +          <img class="product-card-image" src="images/Green.jpg" width="300px" height="211px" alt="GreenTree Inn">
размеры должны быть без единиц измерения

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +        <a class="product-card-button button" href="#">В избранное</a>
здесь другой текст в макете

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +        <a class="product-card-button button" href="#">В избранном</a>
здесь другой текст в макете

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      </li>
не размечены звезды и рейтинг

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +      </p>
здесь нужна форма вместо p

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +          <img src="./images/social-VK.svg" width="24" height="14" alt="Вконтакте">
ошибка в имени файла. Такого файла нет. Есть файл Social-VK.svg

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +          <img src="./images/social-youtube.svg" width="22" height="17" alt="Ютуб">
ошибка в имени файла. Такого файла нет. Есть файл Social-youtube.svg

2022-05-31 14:10 UTC, mkolotovich commented on catalog.html
> +        height="32.9" alt="Логотип академии">
значениями должны быть целыми числами

2022-06-01 05:32 UTC, mkolotovich commented on index.html
> +            <span class="visually-hidden">Хочу сюда!</span>
нельзя вкладывать один интерактивный элемент внутрь другого, валидатор будет ругаться. Используйте здесь либо ссылку либо кнопку

2022-06-01 05:41 UTC, mkolotovich commented on index.html
>          <li class="advantages-content">Небольшая
это слово должно быть в одном теге со следующим словом

2022-06-01 05:41 UTC, mkolotovich commented on index.html
>            <p>дорога</p>
это одна фраза не нужно её разбивать по параграфам

2022-06-01 05:41 UTC, mkolotovich commented on index.html
>            <p>туристов</p>
тоже самое. Это одна фраза и она должна быть внутри одно тега

2022-06-01 05:41 UTC, mkolotovich commented on catalog.html
> +            <span class="visually-hidden">Хочу сюда!</span>
тут либо кнопка должна быть либо ссылка

2022-06-01 05:50 UTC, mkolotovich commented on catalog.html
> +      <button>Сбросить</button>
здесь должна быть одна форма, а не несколько форм

2022-06-01 05:55 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки плюс добавились новые. После слова Гостиницы на странице каталога не должно быть символа > по макету.

2022-06-03 05:59 UTC, mkolotovich commented on index.html
>          <li class="advantages-content">Небольшая
одним тегом нужно было обернуть текст - Небольшая площадь, вторым  — №3 —, а третьим - Все достопримечательности находятся очень близко. Зачем всё в один тег сложили?

2022-06-03 06:00 UTC, mkolotovich requested changes
Исправьте не схлопнутые комментарии с прошлых проверок

2022-06-07 12:41 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлых проверок плюс добавилось новое.

2022-06-07 12:41 UTC, mkolotovich commented on index.html
> +          <br>Мало туристов</p>
Тут другой открывающий тег, который не совпадает с закрывающим.

2022-06-07 12:45 UTC, Moonfaction commented on index.html
> +          <br>Мало туристов</p>
Исправил

2022-06-07 13:02 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлых проверок

2022-06-07 13:29 UTC, mkolotovich requested changes
исправьте один комментарий и я приму ваш ПР

2022-06-07 13:29 UTC, mkolotovich commented on catalog.html
> +      <form>
форма должна начинаться сразу после заголовка, так как текст Инфраструктура тоже относится к форме

2022-06-07 14:05 UTC, merged